---

- name: Verify if Swarm is started
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Add manager to the Swarm
  shell: docker swarm join --token {{ hostvars['manager_token']['stdout'] }} {{ hostvars['swarm-manager']['ansible_default_ipv4']['address'] }}:2377
  when: swarm_status.rc != 0
  tags: swarm