---

- name: Docker Swarm leave
  become: yes
  shell: docker swarm leave --force
  ignore_errors: yes

- name: Kill containers and prune 
  become: yes
  shell: docker stop registry && docker container prune -f && docker image prune -f && docker volume prune -f && docker network prune -f && docker system prune -f

- name: Unistall Docker
  become: yes
  shell: python3 -m pip uninstall docker -y