---

- name: Check if the swarm is started
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm
  
- name: Initialize docker swarm
  shell: >
        docker swarm init --advertise-addr={{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:2377
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Get manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token
  tags: swarm

- name: Get worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm